### ISSUE TITLE
Legend isn't working as expected, appears as undefined 

### ISSUE THREAD

**Issue by Toli97** [sgratzl/chartjs-chart-funnel#4]
When I display legends as visible, they appear as undefined. I just used the namespace **options.plugins.legend** and the **display** option as mentioned in [ChartJS configuration](https://www.chartjs.org/docs/latest/configuration/legend.html).

**Reproduction link**

[Codepen example](https://codepen.io/Toliveira/pen/oNMMVNE)

**Expected behavior**

Legends should show the same as the label. (In the example, Step 1, Step 2...)

**Image showing the error**

![image](https://user-images.githubusercontent.com/25825741/215451288-af25785d-128f-49b1-85d0-81d83a3c6df9.png)

**Context**

- Version: v4.0.0-alpha1
- Browser: Chrome

**Comment by sgratzl** [comment]
can you clarify? when I enable the plugin and define a label for the dataset it works just fine. 

```js
window.onload = () => {
  const ctx = document.getElementById("canvas").getContext("2d");
  window.myBar = new Chart(ctx, {
    type: 'funnel',
    data: {
      labels: ['Step 1', 'Step 2', 'Step 3'],
      datasets: [{
        label: 'Dataset 1',
        data: [1, 0.75, 0.5]
      }]
    },
    options: {
      indexAxis: 'y',
      title: {
        display: true,
        text: 'Chart.js Funnel Chart'
      },
      plugins: {
        legend: {
          display: true
        }
      }
    },
    plugins: [ChartDataLabels],
  });

};
```

**Comment by Toli97** [comment]
> can you clarify? when I enable the plugin and define a label for the dataset it works just fine.
> 
> ```js
> window.onload = () => {
>   const ctx = document.getElementById("canvas").getContext("2d");
>   window.myBar = new Chart(ctx, {
>     type: 'funnel',
>     data: {
>       labels: ['Step 1', 'Step 2', 'Step 3'],
>       datasets: [{
>         label: 'Dataset 1',
>         data: [1, 0.75, 0.5]
>       }]
>     },
>     options: {
>       indexAxis: 'y',
>       plugins: {
>         title: {
>         display: true,
>           text: 'Chart.js Funnel Chart'
>         },
>         legend: {
>           display: true
>         }
>       }
>     },
>     plugins: [ChartDataLabels],
>   });
> 
> };
> ```

Isn't there any way to use the labels as legends instead of the datasets?
In your example the legend is for Dataset 1. Can the legends be Step 1; Step 2 and Step 3 with each corresponding color?

Thank you for your response.

**Comment by sgratzl** [comment]
you are asking about a categorical color legend?

similar to https://github.com/sgratzl/chartjs-chart-geo 
![image](https://user-images.githubusercontent.com/4129778/215499134-89b04fec-dfe8-4e6a-ad00-363c37a3e49b.png)
bottom right color legend but for the categories (Step 1, Step 2, Step 3)?

AFAIK there is no chartjs plugin that currently implements something like this. This plugin implements a funnel chart using a single dataset consisting of multiple data points. Not sure whether it could be swapped the other way around, since internally different datasets are handled independently making the stepping effect quite difficult.

**Comment by Toli97** [comment]
> you are asking about a categorical color legend?
> 
> similar to https://github.com/sgratzl/chartjs-chart-geo ![image](https://user-images.githubusercontent.com/4129778/215499134-89b04fec-dfe8-4e6a-ad00-363c37a3e49b.png) bottom right color legend but for the categories (Step 1, Step 2, Step 3)?
> 
> AFAIK there is no chartjs plugin that currently implements something like this. This plugin implements a funnel chart using a single dataset consisting of multiple data points. Not sure whether it could be swapped the other way around, since internally different datasets are handled independently making the stepping effect quite difficult.

Yeah, i figured. 

I'll see what I can do but I appreciate your answer. Thank you for the help.

Cheers.
